name: 'Test Fetch Latest Github Tag'

on:
  push:
  pull_request:
    branches: ['main']
  workflow_dispatch:

jobs:
  test-fetch-latest-github-tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Fetch Latest GitHub Tag
      id: fetch-latest-tag
      uses: './'
      with:
        owner: 'brainxio'
        repo: 'actions'

    - name: Print Latest Tag
      run: echo "Latest Tag ${{ env.GH_LATEST_TAG }}"

    - name: Print Latest Tag
      run: echo "Latest Tag ${{ steps.fetch-latest-tag.outputs.latest-tag }}"
